# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmoparrot
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmoparrot
  template:
    metadata:
      labels:
        app: cosmoparrot
    spec:
      containers:
      - name: cosmoparrot-container
        image: cosmoparrot:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: COSMOPARROT_PORT
          value: "8080"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: cosmoparrot
  namespace: platform
spec:
  selector:
    app: cosmoparrot
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
