# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: cosmoparrot
description: A Helm cosmoparrot for deploying Cosmoparrot
type: application
version: 0.1.0
appVersion: "latest"
