# Copyright 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: Go Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.12-dind
        ports:
          - 2375:2375
          - 9094:9094
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16  # v6
        with:
          go-version: stable

      - name: Run go test
        run: go test -v ./...
